@startuml

entity Manager {
    +ID_Manager: int
    +Nama_Manager: string
    +Email_Manager: string
    +No_Telephone_Manager: string
}

entity Pembayaran {
    +ID_Pembayaran: int
    +Jumlah_Pembayaran: float
    +Tanggal_Pembayaran: date
    +Metode_Pembayaran: string
}

entity Customer {
    +ID_Customer: int
    +Nama_Customer: string
    +Email_Customer: string
    +No_Telephone_Customer: string
    +Alamat_Customer: string
    +Kecamatan: string
    +Kota: string
    +Kode_Pos: string
    +Preferensi_Customer: string
    +Status_Keanggotaan_Customer: string
}

entity Reservasi {
    +ID_Reservasi: int
    +Waktu_Reservasi: datetime
    +Status_Reservasi: string
}

entity Capster {
    +ID_Capster: int
    +Nama_Capster: string
    +Spesialisasi_Capster: string
    +Rating_Capster: float
    +Ketersediaan_Capster: string
}

entity Model_Rambut {
    +ID_Model: int
    +Nama_Model: string
    +Kategori_Model: string
    +Deskripsi_Model: string
    +Harga_Model: float
}

entity Antrian {
    +ID_Antrian: int
    +Nomor_Antrian: int
    +Status_Antrian: string
}

entity Inventaris {
    +ID_Inventaris: int
    +Nama_Inventaris: string
    +Status_Kerusakan_Inventaris: string
    +Jumlah_Inventaris: int
}

entity Promo {
    +ID_Promo: int
    +Deskripsi_Promo: string
    +Diskon_Promo: float
    +Tgl_Mulai_Promo: date
    +Tgl_Selesai_Promo: date
}

Manager --|> Pembayaran : "Mengelola"
Manager --|> Inventaris : "Mengelola"
Manager --|> Promo : "Membuat"

Customer --|> Pembayaran : "Melakukan"
Customer --|> Reservasi : "Membuat"
Customer --|> Model_Rambut : "Memilih"

Reservasi --|> Capster : "ID_Capster"
Reservasi --|> Model_Rambut : "ID_Model"
Reservasi --|> Customer : "ID_Pelanggan"

Antrian --|> Customer : "ID_Pelanggan"
Antrian --|> Antrian : "ID_Antrian"

Capster --|> Reservasi : "Menangani"

@enduml
