@startuml ERD
entity "Anak" as Anak {
  +anak_id: INT <<PK>>
  nama: VARCHAR
  tanggal_lahir: DATE
  alamat: VARCHAR
  orang_tua_id: INT <<FK>>
}

entity "OrangTuaWali" as OrangTuaWali {
  +orang_tua_id: INT <<PK>>
  nama: VARCHAR
  alamat: VARCHAR
  nomor_telepon: VARCHAR
}

entity "Staf" as Staf {
  +staf_id: INT <<PK>>
  nama: VARCHAR
  posisi: VARCHAR
  jadwal_kerja: VARCHAR
}

entity "Jadwal" as Jadwal {
  +jadwal_id: INT <<PK>>
  tanggal: DATE
  kegiatan: VARCHAR
}

entity "Laporan" as Laporan {
  +laporan_id: INT <<PK>>
  tanggal: DATE
  jenis: VARCHAR
  isi: TEXT
}

Anak }|..|| OrangTuaWali : "dari"
Jadwal ||--o{ Staf : "di managed oleh"
Staf ||--o{ Laporan : "membuat"
OrangTuaWali ||--o{ Laporan : "melihat"
@enduml
