@startuml
actor Pelanggan
actor Pegawai

rectangle "Manajemen" {
  Pelanggan --> DataPel
  DataPel --> DBPel
  DBPel --> DataPel

  Pelanggan --> Reservasi
  Reservasi --> DBReservasi
  DBReservasi --> Reservasi

  Pelanggan --> Pembayaran
  Pembayaran --> DBPembayaran
  DBPembayaran --> Pembayaran

  AntrianPijat --> DBReservasi
  DBReservasi --> AntrianPijat
  AntrianPijat --> Pelanggan

  Pegawai --> AntrianPijat

  QandN --> DBQandN
  DBQandN --> QandN
  QandN --> Reservasi

  Manajemen -> Reservasi
}
@enduml
